### ISSUE TITLE
disabled should not change mouse cursor

### ISSUE THREAD

**Issue by tomByrer** [abpetkov/powerange#1]
EG, don't show the 4-directions cursor when hovering over the disabled slider.

Thanks for the cool lib!

**Comment by abpetkov** [comment]
Thanks for the feedback! I'll include this in the next version.

Cheers.

**Comment by abpetkov** [comment]
Showing default cursor on disabled slider, updated on <a href="https://github.com/abpetkov/powerange/releases/tag/0.0.2">release 0.0.2</a>

**Comment by tomByrer** [comment]
Perfect, cheers.
