### ISSUE TITLE
How to Use the slider for iterating it in a loop

### ISSUE THREAD

**Issue by srshkmr** [abpetkov/powerange#14]
How do I make the slider to work when I have a loop to create multiple sliders .
I have used switchery and there is an option for making it inside an array using 
var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));
  elems.forEach(function(html) {
      var switchery = new Switchery(html);
});

So how do i do this for the slider without this only the first slider gets displayed and rest of the slider look like the default one

**Comment by abpetkov** [comment]
It's the same approach, something must be wrong with your code. Here's an <a href="http://jsfiddle.net/64dq1wwh/" target="_blank">example</a>.
